# Generated by Django 2.2.6 on 2019-10-30 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Postagem')),
            ],
        ),
    ]
